modLoader = "javafml"
loaderVersion = "[48,)"
#issueTrackerURL = ""
license = "ARR"

[[mods]]
modId = "meadow"
version = "${version}"
displayName = "Meadow"
authors = ["satisfy", "Cristelknight999", "BMJO"]
description = '''
A small mod Vanilla+ Mod that aims to improve the meadow biome and adds a new way to create food.
It also brings back a few animals from Minecraft:Earth and gives them a reason to be there beside of looking pretty.
'''
logoFile = "pack.png"

[[dependencies.meadow]]
modId = "forge"
mandatory = true
versionRange = "[48,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.meadow]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.meadow]]
modId = "architectury"
mandatory = true
versionRange = "[10.0.8,)"
ordering = "AFTER"
side = "BOTH"



[[dependencies.meadow]]
modId = "doapi"
mandatory = true
versionRange = "[1.3.0,)"
ordering = "AFTER"
side = "BOTH"