modLoader = "javafml"
loaderVersion = "[46,)"
license = "Custom"

[[mods]]
modId = "meadow"
version = "${version}"
displayName = "Meadow"
authors = ["satisfy", "Cristelknight999", "BMJO"]
description = '''
A small Mod that aims to improve the meadow biome and adds a new way to create food. It also brings back a few animals from Minecraft:Earth and gives and make them actually useful.'''
logoFile = "pack.png"

[[dependencies.meadow]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.meadow]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.meadow]]
modId = "architectury"
mandatory = true
versionRange = "[6.5.77,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.meadow]]
modId = "doapi"
mandatory = true
versionRange = "[1.2.9,)"
ordering = "AFTER"
side = "BOTH"